name: cd

on:
  push:
    branches: [ master-ru ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2.3.1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}


    - name: Installing my packages
      run: npm ci

    - name: Build my App
      run: npm run build
      env:
        NEXT_PUBLIC_BASE_PATH: /tailwindcss.su
    - run: npm run export
      env:
        NEXT_PUBLIC_BASE_PATH: /tailwindcss.su
    - run: touch ./out/.nojekyll
    - run: echo tailwindcss.su >> ./out/CNAME

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: out